#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : libkeduvocdocument
Version  : 18.08.0
Release  : 1
URL      : https://download.kde.org/stable/applications/18.08.0/src/libkeduvocdocument-18.08.0.tar.xz
Source0  : https://download.kde.org/stable/applications/18.08.0/src/libkeduvocdocument-18.08.0.tar.xz
Source99 : https://download.kde.org/stable/applications/18.08.0/src/libkeduvocdocument-18.08.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 LGPL-2.0
Requires: libkeduvocdocument-lib
Requires: libkeduvocdocument-license
Requires: libkeduvocdocument-locales
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : qtbase-dev qtbase-extras mesa-dev

%description
Contents of libkeduvocdocument as of July 2014, and brief description of each module:

%package dev
Summary: dev components for the libkeduvocdocument package.
Group: Development
Requires: libkeduvocdocument-lib
Provides: libkeduvocdocument-devel

%description dev
dev components for the libkeduvocdocument package.


%package lib
Summary: lib components for the libkeduvocdocument package.
Group: Libraries
Requires: libkeduvocdocument-license

%description lib
lib components for the libkeduvocdocument package.


%package license
Summary: license components for the libkeduvocdocument package.
Group: Default

%description license
license components for the libkeduvocdocument package.


%package locales
Summary: locales components for the libkeduvocdocument package.
Group: Default

%description locales
locales components for the libkeduvocdocument package.


%prep
%setup -q -n libkeduvocdocument-18.08.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535236265
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1535236265
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libkeduvocdocument
cp COPYING %{buildroot}/usr/share/doc/libkeduvocdocument/COPYING
cp COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/doc/libkeduvocdocument/COPYING-CMAKE-SCRIPTS
cp COPYING.LIB %{buildroot}/usr/share/doc/libkeduvocdocument/COPYING.LIB
pushd clr-build
%make_install
popd
%find_lang libkeduvocdocument

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libkeduvocdocument/KEduVocArticle
/usr/include/libkeduvocdocument/KEduVocConjugation
/usr/include/libkeduvocdocument/KEduVocContainer
/usr/include/libkeduvocdocument/KEduVocDeclension
/usr/include/libkeduvocdocument/KEduVocDocument
/usr/include/libkeduvocdocument/KEduVocExpression
/usr/include/libkeduvocdocument/KEduVocIdentifier
/usr/include/libkeduvocdocument/KEduVocKVTML2Writer
/usr/include/libkeduvocdocument/KEduVocLeitnerBox
/usr/include/libkeduvocdocument/KEduVocLesson
/usr/include/libkeduvocdocument/KEduVocMultipleChoice
/usr/include/libkeduvocdocument/KEduVocPersonalPronoun
/usr/include/libkeduvocdocument/KEduVocText
/usr/include/libkeduvocdocument/KEduVocTranslation
/usr/include/libkeduvocdocument/KEduVocWordFlags
/usr/include/libkeduvocdocument/KEduVocWordtype
/usr/include/libkeduvocdocument/SharedKVTMLFiles
/usr/include/libkeduvocdocument/keduvocarticle.h
/usr/include/libkeduvocdocument/keduvocconjugation.h
/usr/include/libkeduvocdocument/keduvoccontainer.h
/usr/include/libkeduvocdocument/keduvocdeclension.h
/usr/include/libkeduvocdocument/keduvocdocument.h
/usr/include/libkeduvocdocument/keduvocdocument_export.h
/usr/include/libkeduvocdocument/keduvocexpression.h
/usr/include/libkeduvocdocument/keduvocidentifier.h
/usr/include/libkeduvocdocument/keduvockvtml2writer.h
/usr/include/libkeduvocdocument/keduvocleitnerbox.h
/usr/include/libkeduvocdocument/keduvoclesson.h
/usr/include/libkeduvocdocument/keduvocmultiplechoice.h
/usr/include/libkeduvocdocument/keduvocpersonalpronoun.h
/usr/include/libkeduvocdocument/keduvoctext.h
/usr/include/libkeduvocdocument/keduvoctranslation.h
/usr/include/libkeduvocdocument/keduvocwordflags.h
/usr/include/libkeduvocdocument/keduvocwordtype.h
/usr/include/libkeduvocdocument/sharedkvtmlfiles.h
/usr/lib64/cmake/libkeduvocdocument/LibKEduVocDocumentConfig.cmake
/usr/lib64/cmake/libkeduvocdocument/LibKEduVocDocumentTargets-relwithdebinfo.cmake
/usr/lib64/cmake/libkeduvocdocument/LibKEduVocDocumentTargets.cmake
/usr/lib64/libKEduVocDocument.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKEduVocDocument.so.5
/usr/lib64/libKEduVocDocument.so.5.0.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/libkeduvocdocument/COPYING
/usr/share/doc/libkeduvocdocument/COPYING-CMAKE-SCRIPTS
/usr/share/doc/libkeduvocdocument/COPYING.LIB

%files locales -f libkeduvocdocument.lang
%defattr(-,root,root,-)

